### PR TITLE
[WIP] Code Redesign

### PR DESCRIPTION
**Pull request by xetys**
As stated in #47 here comes the next big thing. It contains a huge package redesign, decoupling the kubernetes installation from cobra and hetzner. The PR also adds the vendor lib to the source, as I want to ensure build stability and reproducibility

### CODE REVIEW

**Comment by JohnnyQQQQ** [comment]
@xetys If I can help you in any way to get this PR landed just drop me a line

**Comment by xetys** [comment]
Feel free to help. I already did a heavy lifting part and I tested the basic cluster create runs. But there are a lot of issues with the different sub-commands. As my time is low again, I would be happy to any help.

Even adding more tests would be a great help. For example, we could mock the NodeCommunicator interface with a pseudo-ssh client, to do integration tests for the cluster manager.

**Comment by xetys** [comment]
so, I think this is a good state for now. I tested the common scenarios. The test coverage slightly increased, but codeclimate is telling a lot of issues. 

@JohnnyQQQQ could you please test the current state in this branch before I merge?

**Comment by JohnnyQQQQ** [comment]
@xetys when creating a cluster I can't input the ssh-key passphrase, it seems to be buggy.

**Comment by JohnnyQQQQ** [comment]
buggy_input

It seems like the change of asking first for the passphrase when doing something that is passphrase related is missing.

**Comment by xetys** [comment]
OK, this also working now, so I think it's time to merge this

**Pull request merged**
