### PR TITLE
Addon docker registry

### PR DESCRIPTION
**Pull request by lilvinz**
* adds docker-registry addon and configures it for persistent storage
* requires PVC support in cluster e.g. by Rook

### CODE REVIEW

**Comment by lilvinz** [comment]
Hm, it seems a storage class for the PVC has to be set. This needs some more testing before merge.

**Comment by pierreozoux** [comment]
@lilvinz if you use rook, the storage-class should be:

`rook-block`

https://github.com/rook/rook/blob/master/cluster/examples/kubernetes/rook-storageclass.yaml#L18

**Comment by pierreozoux** [comment]
@xetys you see that's why I think it would be easier to be opinionated, then we can create an ecosystem that we know work well together. 

So I do agree with you that addons are not just a wrapper around helm, because, we can customize them to our particular needs. But if we offer too much options, it will increase the complexity, and it will be difficult to maintain.

**Comment by lilvinz** [comment]
@pierreozoux I agree. I was exactly hesitating to pre-define a storage class because there are at least two, which should currently be supported.

So @xetys what is it you would like to see? Shall i set rook by default and note that in the README.md or shall i add an option and force the user to make a choice?

**Comment by lilvinz** [comment]
Another alternative would be to set rook-block or anything else as cluster default. That is then automatically being chosen.

**Comment by pierreozoux** [comment]
Or an other way of solving, make rook and other storage options create the same storage class (like `ssd` ) In this case, it would be easier to consume later on.

**Comment by xetys** [comment]
Anyways, you must pass the storageClassName to the helm chart if you want to consume it. Or your cluster has a default storage class. But here I think it's better not to set up the storage providers as default per default. You could install both, rook and OpenEBS. If they set the default flag, you will have less control over this question. So I think the proper way should be:

1. Install either `addon install rook --set-default` or `addon install openebs --set-default` 
2. Install `addon install docker-registry` should check, if there is a default storage class, and fail if not.

WDYT?

**Comment by pierreozoux** [comment]
I forgot about default storage class :)

Then, IMHO:
 - when the cluster admin installs a storage plugin, it should be the default storage class, if you want, we could have a switch to allow people to not set it as default, but I think most of people want a default storage and just one storage (except for testing, or complicated setup, that this tool shouldn't cover in my opinion)
 - for the addon to check if there is a default storage class, I don't think it should. It should check if there is a storage provider addon, yes.

Actually, I see that this plugin could also consume s3 :) I think also that it would be more cloud native to consume s3 than regular fs. Rook does provide this. But this is maybe out of the scope of this PR.

**Comment by xetys** [comment]
> Actually, I see that this plugin could also consume s3 :) I think also that it would be more cloud native to consume s3 than regular fs. Rook does provide this. But this is maybe out of the scope of this PR.

Yes, definitely. I don't even know how stable the S3 support from rook is.

So as I get, you want if either rook or OpenEBS are installed, they get marked `default`, if the user doesn't pass some kind of `--no-default` flag?

**Comment by pierreozoux** [comment]
@xetys Yes, I think this would make sense.

(I'm working on [that](https://github.com/rook/rook/pull/1545) to have a proper helm chart for the rook cluster, and be able to set it as default easily)

In the mean time, it might be easier to copy the rook-storage to this repo, with the default set, and point the addon to our local file?

WDYT?

**Comment by xetys** [comment]
I would do it the easy way:

```
# kubectl patch storageclass rook-block -p '{"metadata": {"annotations":{"storageclass.kubernetes.io/is-default-class":"true"}}}'
```

you can either do something like
```
# kubectl get storageclass | grep -v 'NAME' | awk '{print$1}' | xargs kubectl patch storageclass -p '{"metadata": {"annotations":{"storageclass.kubernetes.io/is-default-class":"false"}}}'
```
 before for removing all other storageclasses default flag in advance. With this, you won't end up having multiple default classes

**Comment by pierreozoux** [comment]
@xetys something like this then? https://github.com/xetys/hetzner-kube/pull/55
:P

**Comment by xetys** [comment]
as #55 is merged, @lilvinz could you please verify it's now working. If everything is alright, please remove the WIP and I merge it

**Comment by lilvinz** [comment]
This works for me although to get basic authentication working another parameter has to be passed to helm. This might be handled in a separate PR though.

**Pull request merged**
