### PR TITLE
use go.mod for dependencies

### PR DESCRIPTION
**Pull request by JohnnyQQQQ**

### CODE REVIEW

**Comment by xetys** [comment]
quickly for me

what's the deal of choosing go.mod over dep?

**Comment by JohnnyQQQQ** [comment]
using `go mod` is the official approach introduced in golang 1.11 for handling dependencies and getting rid of the need to have the project in to GOPATH

https://github.com/golang/go/wiki/Modules

**Comment by mavimo** [comment]
@JohnnyQQQQ some reference to make the CI work with Go 1.10 and 1.11 at the same time https://arslan.io/2018/08/26/using-go-modules-with-vendor-support-on-travis-ci/

**Comment by xetys** [comment]
like already discussed with @mavimo I'm ok with dropping support for go <1.11, as we are not in a stable major version >= 1.0.0, and hetzner-kube more a tool than a framework.

So IMHO we can bring this PR on go 1.11 only with go mod as one package management solution.

**Comment by mavimo** [comment]
@JohnnyQQQQ if needed I can work on it, let me know if you have time to complete this task :)

**Comment by JohnnyQQQQ** [comment]
@mavimo feel free to pick it up, I don't have much time to work on it right now

**Pull request closed without merging**
