### PR TITLE
Update flannel url to use master branch to enable hostPort support

### PR DESCRIPTION
**Pull request by Doccrazy**
This updates the flannel installation URL to https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml, as documented on https://github.com/coreos/flannel. 

This includes the changes from https://github.com/coreos/flannel/pull/888, which enables the CNI portmap plugin to allow hostPort mappings, as required e.g. for the Traefik helm chart. 
Flannel is hard to upgrade in an existing cluster, as config files need to be manually removed and a reboot is required.

### CODE REVIEW

**Comment by pierreozoux** [comment]
Undertand, but still, I think this would be better to point to one version, like `v0.10.0`, and update this version regularly.

What do you think?

**Comment by Doccrazy** [comment]
My understanding is that the flannel config file (from Documentation folder, not directly from source) is explicitly updated by the maintainers on new releases to refer to the latest stable version. 
See e.g. https://github.com/coreos/flannel/blob/c0648a8ff42002d7f3ab2292f79e07584e2bd8a0/Documentation/kube-flannel.yml#L107 and the commit history of that file.

**Comment by pierreozoux** [comment]
Yes, this is the problem, we don't want to ship a new version without knowing it explicitly, this is a good practice.

**Comment by Doccrazy** [comment]
I don't really care which version is used. 0.10.0 includes the portmap fix, so this is fine by me.

**Comment by xetys** [comment]
Hey! Good hint. Could you please open this PR for the redesign branch?

**Comment by Doccrazy** [comment]
Sure, I updated the PR (first time using this feature, yay!)

**Comment by xetys** [comment]
hey, thanks for your PR.

The redesign is current WIP and one of the parts is totally making `nodeUtil.go` obsolete. The new stuff happens in `pkg/cluster/manager.go`. It's logically the same. Could you please fix this last point? Sorry for confusing

**Comment by mavimo** [comment]
@xetys I think we can close this issue

**Comment by mavimo** [comment]
@xetys @Doccrazy @pierreozoux there is something missing from the #124 or we can close this PR?

**Comment by mavimo** [comment]
@xetys @Doccrazy @pierreozoux 🆙

**Comment by mavimo** [comment]
I think we can close it, open it again if I'm wrong, thx!

**Pull request closed without merging**
