### PR TITLE
[WIP] Fix add worker

### PR DESCRIPTION
**Pull request by JohnnyQQQQ**
closes partly #99

### CODE REVIEW

**Comment by JohnnyQQQQ** [comment]
I'm fixing the last issue. It's with the register node task. I think the certs are missing somehow...

```log
May 29 16:11:21 production-worker-04 kubelet[12336]: F0529 16:11:21.515541   12336 server.go:218] unable to load client CA file /etc/kubernetes/pki/ca.crt: open /etc/kubernetes/pki/ca.crt: no such file or directory
May 29 16:11:21 production-worker-04 systemd[1]: kubelet.service: Main process exited, code=exited, status=255/n/a
May 29 16:11:21 production-worker-04 systemd[1]: kubelet.service: Unit entered failed state.
May 29 16:11:21 production-worker-04 systemd[1]: kubelet.service: Failed with result 'exit-code'.
```

**Comment by xetys** [comment]
i think if the progress bar is the only issue I can merge this, so the very basic stuff gets working

LGTM

**Comment by vpm-bradleyhession** [comment]
Adding an external node results in:

panic: runtime error: slice bounds out of range

goroutine 1 [running]:
github.com/xetys/hetzner-kube/pkg/clustermanager.PrivateIPPrefix(0x0, 0x0, 0xc420206610, 0xa)
	/root/go/src/github.com/xetys/hetzner-kube/pkg/clustermanager/wireguard.go:61 +0xad
github.com/xetys/hetzner-kube/cmd.glob..func3(0xb974a0, 0xc42001d140, 0x0, 0x4)
	/root/go/src/github.com/xetys/hetzner-kube/cmd/cluster_add_external_worker.go:133 +0x4b7
github.com/xetys/hetzner-kube/vendor/github.com/spf13/cobra.(*Command).execute(0xb974a0, 0xc42001d100, 0x4, 0x4, 0xb974a0, 0xc42001d100)
	/root/go/src/github.com/xetys/hetzner-kube/vendor/github.com/spf13/cobra/command.go:702 +0x2bd
github.com/xetys/hetzner-kube/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xb998c0, 0xc42014a9c5, 0x0, 0x0)
	/root/go/src/github.com/xetys/hetzner-kube/vendor/github.com/spf13/cobra/command.go:783 +0x349
github.com/xetys/hetzner-kube/vendor/github.com/spf13/cobra.(*Command).Execute(0xb998c0, 0x91c952, 0x5)
	/root/go/src/github.com/xetys/hetzner-kube/vendor/github.com/spf13/cobra/command.go:736 +0x2b
github.com/xetys/hetzner-kube/cmd.Execute()
	/root/go/src/github.com/xetys/hetzner-kube/cmd/root.go:51 +0x82
main.main()
	/root/go/src/github.com/xetys/hetzner-kube/main.go:20 +0x20

**Comment by vpm-bradleyhession** [comment]
Ok so external workers is still broken (missed the comment) do we have any pointers as to why yet?

**Pull request merged**
