### PR TITLE
refs #225: add support for ZSH completion

### LINKED ISSUE #225: Support zsh for completion
Even with `autoload -U +X bashcompinit && bashcompinit`, the completion does not work with zsh, because `type -t` does not exist. I'm not sure what the correct command is for zsh, unfortunately.

### PR DESCRIPTION
**Pull request by mavimo**
Closes #225

@jcassee I added support for ZSH completion, can you check if it work as expected? Thanks!

### CODE REVIEW

**Comment by mavimo** [comment]
@jcassee I'm not a ZSH user so it's a bit hard to me to investigate and debug it, can you take a look to the discussion reported in https://github.com/gopasspw/gopass/issues/585 and indicate me if you can find some solution (so I can update the readme on this PR)? Thx!!

**Comment by jcassee** [comment]
Ah, it's a completion file, not something that can be sourced. I am not sure how to convert it, but this worked:
```
hetzner-kube completion zsh >| ~/.zcomp/_hetzner-kube
fpath=($HOME/.homesick/repos/homeshick/completions $fpath)
rm -f ~/.zcompdump
compinit
```

This might be good enough?

**Comment by mavimo** [comment]
@jcassee thx!! 🎉

**Comment by jcassee** [comment]
@mavimo Thank you for the PR.

I see copied the wrong piece of command line history. Fixed it now.

**Comment by xetys** [comment]
LGTM

**Comment by mavimo** [comment]
@xetys hemm.. i need to fix the docs 😄 

I'll open a new PR asap

**Pull request merged**
