### PR TITLE
adding cloud-init script to add-worker cmd

### PR DESCRIPTION
**Pull request by drallgood**
This allows a custom user-init scripts to be used when adding new nodes, e.g. to set up floating IPs or things like ansible.

I mostly tried copying what was already there. Suggestions are always very welcome.

### CODE REVIEW

**Comment by xetys** [comment]
hey,

what is the use-case here? You create a cluster without cloud-init, but then add a cloud-init for a worker, do I get this right? Did you try if that works?

**Comment by drallgood** [comment]
@xetys
Exactly. Or you want a different config than before for these workers. 

Yes, it works. used it twice yesterday

**Comment by drallgood** [comment]
@xetys Is that something you want to incorporate?

**Comment by xetys** [comment]
thanks for reminding me...

LGTM

**Pull request merged**
