### PR TITLE
allow to write file that can be accessed only from owner and use this config for wireguard

### LINKED ISSUE #165: World-readable PrivateKey in /etc/wireguard/wg0.conf
The directory `/etc/wireguard` and the file `/etc/wireguard/wg0.conf` are both world-readable, possibly exposing the `PrivateKey=` to components/users which shouldn't have access to it.

```
root@grfy-k8s-cab0-master-01 /etc/wireguard # ls -ld /etc/wireguard/
drwxr-xr-x 2 root root 4096 May  9 23:40 /etc/wireguard/
root@grfy-k8s-cab0-master-01 /etc/wireguard # ls -l /etc/wireguard/wg0.conf 
-rw-r--r-- 1 root root 989 Jul 12 01:21 /etc/wireguard/wg0.conf
```

### PR DESCRIPTION
**Pull request by mavimo**
Closes #165 

 - allow to write file that can be accessed only from owner
 - wireguard config can be accessed only from owner when created

### CODE REVIEW

**Comment by mavimo** [comment]
@eliasp can you confirm that current version of code will fix the issue you reported? I tried to create a cluster and work as expected

**Comment by mavimo** [comment]
@xetys rebased

**Comment by xetys** [comment]
I'm so sorry...it has to be done again :/

**Comment by xetys** [comment]
There was a failing build caused by the change...Maybe you find time to check what's wrong there?

**Comment by mavimo** [comment]
@xetys I'll try to check ASAP

**Comment by mavimo** [comment]
@xetys rebased

**Pull request merged**
